### ISSUE TITLE
Skill tree is not complete

### ISSUE THREAD

**Issue by kedare** [bluefeet/Games-EveOnline-API#5]
Hello,

I'm trying to develop a script that use datas from the Skill Tree. Unfortunatelly, I only get a limited views  of the skills.

Here is the code I use to to my request : 

```
try {
  $eve = Games::EveOnline::API->new(
    user_id => $eve_key_id,
    api_key => $eve_verification_code,
  );
} catch {
  warn "Failed to connect to EVE : $_";
};

my $skill_tree;
my $in_training = $eve->skill_in_training( character_id => $eve_character_id );
my $skills = {};

if (-e $cache_file) {
  $skills = YAML::LoadFile($cache_file);
} else {
  warn "No cache file found, building skills resolution\n";
  $skill_tree = $eve->skill_tree();

  say Data::Dumper::Dumper($skill_tree);

  for my $group_id (keys $skill_tree) {
    unless ($group_id eq "cached_until") {
      for my $skill_id (keys %{ $skill_tree->{$group_id}->{"skills"} }) {
        if (defined $skill_tree->{$group_id}->{"skills"}->{$skill_id}->{"name"}) {
          $skills->{$skill_id} = $skill_tree->{$group_id}->{"skills"}->{$skill_id}->{"name"};
        }
      }
    }
  }
  # Write cache
  # say Data::Dumper::Dumper(@skills);
  YAML::DumpFile($cache_file, $skills);
}
```

When I dump at the line : Data::Dumper::Dumper($skill_tree);
I only see a limited view of the skills (My YAML export has only 64 elements).
(I'm quite new to perl, so maybe I've made a misstake ?)

Any idea ?

Thanks

**Comment by Chipsoid** [comment]
Hi, thanks for issue.

"Powerful" XML::Simple squeezed skill groups by group_id, because original xml from API have several elements with same group_id and different skill_ids.

I rewrite skill_tree to XML::LibXML.  ( https://github.com/Chipsoid/Games-EveOnline-API )

P.S. you locally tests work out with errors? I have Pull request with some features (with the last commit fot your issue), but @bluefeet assures that there is error

**Comment by mathieupoussin** [comment]
Thanks for the fix. I confirm you it's working with your modified API.pm ! :)
Thanks again.

**Comment by bluefeet** [comment]
Closing as this module is officially deprecated.
